# T-tests

## Constraint IF t-tests

### Barabasi

cif.bar.ct1 <- t.test(cif1.constraint,as.numeric(as.data.frame(t(as.data.frame(cif.bar1)))$constraint))
cif.bar.ct2 <- t.test(cif2.constraint,as.numeric(as.data.frame(t(as.data.frame(cif.bar2)))$constraint))
cif.bar.ct3 <- t.test(cif3.constraint,as.numeric(as.data.frame(t(as.data.frame(cif.bar3)))$constraint))
cif.bar.ct4 <- t.test(cif4.constraint,as.numeric(as.data.frame(t(as.data.frame(cif.bar4)))$constraint))
cif.bar.ct5 <- t.test(cif5.constraint,as.numeric(as.data.frame(t(as.data.frame(cif.bar5)))$constraint))
cif.bar.ct6 <- t.test(cif6.constraint,as.numeric(as.data.frame(t(as.data.frame(cif.bar6)))$constraint))
cif.bar.ct7 <- t.test(cif7.constraint,as.numeric(as.data.frame(t(as.data.frame(cif.bar7)))$constraint))
cif.bar.ct8 <- t.test(cif8.constraint,as.numeric(as.data.frame(t(as.data.frame(cif.bar8)))$constraint))
cif.bar.ct9 <- t.test(cif9.constraint,as.numeric(as.data.frame(t(as.data.frame(cif.bar9)))$constraint))
cif.bar.ct10 <- t.test(cif10.constraint,as.numeric(as.data.frame(t(as.data.frame(cif.bar10)))$constraint))
cif.bar.ct11 <- t.test(cif11.constraint,as.numeric(as.data.frame(t(as.data.frame(cif.bar11)))$constraint))
cif.bar.ct12 <- t.test(cif12.constraint,as.numeric(as.data.frame(t(as.data.frame(cif.bar12)))$constraint))
cif.bar.ct13 <- t.test(cif13.constraint,as.numeric(as.data.frame(t(as.data.frame(cif.bar13)))$constraint))
cif.bar.ct14 <- t.test(cif14.constraint,as.numeric(as.data.frame(t(as.data.frame(cif.bar14)))$constraint))
cif.bar.ct15 <- t.test(cif15.constraint,as.numeric(as.data.frame(t(as.data.frame(cif.bar15)))$constraint))
cif.bar.ct16 <- t.test(cif16.constraint,as.numeric(as.data.frame(t(as.data.frame(cif.bar16)))$constraint))
cif.bar.ct17 <- t.test(cif17.constraint,as.numeric(as.data.frame(t(as.data.frame(cif.bar17)))$constraint))
cif.bar.ct18 <- t.test(cif18.constraint,as.numeric(as.data.frame(t(as.data.frame(cif.bar18)))$constraint))
cif.bar.ct19 <- t.test(cif19.constraint,as.numeric(as.data.frame(t(as.data.frame(cif.bar19)))$constraint))
cif.bar.ct20 <- t.test(cif20.constraint,as.numeric(as.data.frame(t(as.data.frame(cif.bar20)))$constraint))
cif.bar.ct21 <- t.test(cif21.constraint,as.numeric(as.data.frame(t(as.data.frame(cif.bar21)))$constraint))
cif.bar.ct22 <- t.test(cif22.constraint,as.numeric(as.data.frame(t(as.data.frame(cif.bar22)))$constraint))

### Erdos

cif.erdos.ct1 <- t.test(cif1.constraint,as.numeric(as.data.frame(t(as.data.frame(erdos.cif1)))$constraint))
cif.erdos.ct2 <- t.test(cif2.constraint,as.numeric(as.data.frame(t(as.data.frame(erdos.cif2)))$constraint))
cif.erdos.ct3 <- t.test(cif3.constraint,as.numeric(as.data.frame(t(as.data.frame(erdos.cif3)))$constraint))
cif.erdos.ct4 <- t.test(cif4.constraint,as.numeric(as.data.frame(t(as.data.frame(erdos.cif4)))$constraint))
cif.erdos.ct5 <- t.test(cif5.constraint,as.numeric(as.data.frame(t(as.data.frame(erdos.cif5)))$constraint))
cif.erdos.ct6 <- t.test(cif6.constraint,as.numeric(as.data.frame(t(as.data.frame(erdos.cif6)))$constraint))
cif.erdos.ct7 <- t.test(cif7.constraint,as.numeric(as.data.frame(t(as.data.frame(erdos.cif7)))$constraint))
cif.erdos.ct8 <- t.test(cif8.constraint,as.numeric(as.data.frame(t(as.data.frame(erdos.cif8)))$constraint))
cif.erdos.ct9 <- t.test(cif9.constraint,as.numeric(as.data.frame(t(as.data.frame(erdos.cif9)))$constraint))
cif.erdos.ct10 <- t.test(cif10.constraint,as.numeric(as.data.frame(t(as.data.frame(erdos.cif10)))$constraint))
cif.erdos.ct11 <- t.test(cif11.constraint,as.numeric(as.data.frame(t(as.data.frame(erdos.cif11)))$constraint))
cif.erdos.ct12 <- t.test(cif12.constraint,as.numeric(as.data.frame(t(as.data.frame(erdos.cif12)))$constraint))
cif.erdos.ct13 <- t.test(cif13.constraint,as.numeric(as.data.frame(t(as.data.frame(erdos.cif13)))$constraint))
cif.erdos.ct14 <- t.test(cif14.constraint,as.numeric(as.data.frame(t(as.data.frame(erdos.cif14)))$constraint))
cif.erdos.ct15 <- t.test(cif15.constraint,as.numeric(as.data.frame(t(as.data.frame(erdos.cif15)))$constraint))
cif.erdos.ct16 <- t.test(cif16.constraint,as.numeric(as.data.frame(t(as.data.frame(erdos.cif16)))$constraint))
cif.erdos.ct17 <- t.test(cif17.constraint,as.numeric(as.data.frame(t(as.data.frame(erdos.cif17)))$constraint))
cif.erdos.ct18 <- t.test(cif18.constraint,as.numeric(as.data.frame(t(as.data.frame(erdos.cif18)))$constraint))
cif.erdos.ct19 <- t.test(cif19.constraint,as.numeric(as.data.frame(t(as.data.frame(erdos.cif19)))$constraint))
cif.erdos.ct20 <- t.test(cif20.constraint,as.numeric(as.data.frame(t(as.data.frame(erdos.cif20)))$constraint))
cif.erdos.ct21 <- t.test(cif21.constraint,as.numeric(as.data.frame(t(as.data.frame(erdos.cif21)))$constraint))
cif.erdos.ct22 <- t.test(cif22.constraint,as.numeric(as.data.frame(t(as.data.frame(erdos.cif22)))$constraint))

### Watts

cif.watts.ct1 <- t.test(cif1.constraint,as.numeric(as.data.frame(t(as.data.frame(watts.cif1)))$constraint))
cif.watts.ct2 <- t.test(cif2.constraint,as.numeric(as.data.frame(t(as.data.frame(watts.cif2)))$constraint))
cif.watts.ct3 <- t.test(cif3.constraint,as.numeric(as.data.frame(t(as.data.frame(watts.cif3)))$constraint))
cif.watts.ct4 <- t.test(cif4.constraint,as.numeric(as.data.frame(t(as.data.frame(watts.cif4)))$constraint))
cif.watts.ct5 <- t.test(cif5.constraint,as.numeric(as.data.frame(t(as.data.frame(watts.cif5)))$constraint))
cif.watts.ct6 <- t.test(cif6.constraint,as.numeric(as.data.frame(t(as.data.frame(watts.cif6)))$constraint))
cif.watts.ct7 <- t.test(cif7.constraint,as.numeric(as.data.frame(t(as.data.frame(watts.cif7)))$constraint))
cif.watts.ct8 <- t.test(cif8.constraint,as.numeric(as.data.frame(t(as.data.frame(watts.cif8)))$constraint))
cif.watts.ct9 <- t.test(cif9.constraint,as.numeric(as.data.frame(t(as.data.frame(watts.cif9)))$constraint))
cif.watts.ct10 <- t.test(cif10.constraint,as.numeric(as.data.frame(t(as.data.frame(watts.cif10)))$constraint))
cif.watts.ct11 <- t.test(cif11.constraint,as.numeric(as.data.frame(t(as.data.frame(watts.cif11)))$constraint))
cif.watts.ct12 <- t.test(cif12.constraint,as.numeric(as.data.frame(t(as.data.frame(watts.cif12)))$constraint))
cif.watts.ct13 <- t.test(cif13.constraint,as.numeric(as.data.frame(t(as.data.frame(watts.cif13)))$constraint))
cif.watts.ct14 <- t.test(cif14.constraint,as.numeric(as.data.frame(t(as.data.frame(watts.cif14)))$constraint))
cif.watts.ct15 <- t.test(cif15.constraint,as.numeric(as.data.frame(t(as.data.frame(watts.cif15)))$constraint))
cif.watts.ct16 <- t.test(cif16.constraint,as.numeric(as.data.frame(t(as.data.frame(watts.cif16)))$constraint))
cif.watts.ct17 <- t.test(cif17.constraint,as.numeric(as.data.frame(t(as.data.frame(watts.cif17)))$constraint))
cif.watts.ct18 <- t.test(cif18.constraint,as.numeric(as.data.frame(t(as.data.frame(watts.cif18)))$constraint))
cif.watts.ct19 <- t.test(cif19.constraint,as.numeric(as.data.frame(t(as.data.frame(watts.cif19)))$constraint))
cif.watts.ct20 <- t.test(cif20.constraint,as.numeric(as.data.frame(t(as.data.frame(watts.cif20)))$constraint))
cif.watts.ct21 <- t.test(cif21.constraint,as.numeric(as.data.frame(t(as.data.frame(watts.cif21)))$constraint))
cif.watts.ct22 <- t.test(cif22.constraint,as.numeric(as.data.frame(t(as.data.frame(watts.cif22)))$constraint))

## Transitivity

### Barabasi

cif.bar.tt1 <- t.test(!is.na(transitivity(cif1, type=c("local"))),as.numeric(as.data.frame(t(as.data.frame(cif.bar1)))$trans))
cif.bar.tt2 <- t.test(!is.na(transitivity(cif2, type=c("local"))),as.numeric(as.data.frame(t(as.data.frame(cif.bar2)))$trans))
cif.bar.tt3 <- t.test(!is.na(transitivity(cif3, type=c("local"))),as.numeric(as.data.frame(t(as.data.frame(cif.bar3)))$trans))
cif.bar.tt4 <- t.test(!is.na(transitivity(cif4, type=c("local"))),as.numeric(as.data.frame(t(as.data.frame(cif.bar4)))$trans))
cif.bar.tt5 <- t.test(!is.na(transitivity(cif5, type=c("local"))),as.numeric(as.data.frame(t(as.data.frame(cif.bar5)))$trans))
cif.bar.tt6 <- t.test(!is.na(transitivity(cif6, type=c("local"))),as.numeric(as.data.frame(t(as.data.frame(cif.bar6)))$trans))
cif.bar.tt7 <- t.test(!is.na(transitivity(cif7, type=c("local"))),as.numeric(as.data.frame(t(as.data.frame(cif.bar7)))$trans))
cif.bar.tt8 <- t.test(!is.na(transitivity(cif8, type=c("local"))),as.numeric(as.data.frame(t(as.data.frame(cif.bar8)))$trans))
cif.bar.tt9 <- t.test(!is.na(transitivity(cif9, type=c("local"))),as.numeric(as.data.frame(t(as.data.frame(cif.bar9)))$trans))
cif.bar.tt10 <- t.test(!is.na(transitivity(cif10, type=c("local"))),as.numeric(as.data.frame(t(as.data.frame(cif.bar10)))$trans))
cif.bar.tt11 <- t.test(!is.na(transitivity(cif11, type=c("local"))),as.numeric(as.data.frame(t(as.data.frame(cif.bar11)))$trans))
cif.bar.tt12 <- t.test(!is.na(transitivity(cif12, type=c("local"))),as.numeric(as.data.frame(t(as.data.frame(cif.bar12)))$trans))
cif.bar.tt13 <- t.test(!is.na(transitivity(cif13, type=c("local"))),as.numeric(as.data.frame(t(as.data.frame(cif.bar13)))$trans))
cif.bar.tt14 <- t.test(!is.na(transitivity(cif14, type=c("local"))),as.numeric(as.data.frame(t(as.data.frame(cif.bar14)))$trans))
cif.bar.tt15 <- t.test(!is.na(transitivity(cif15, type=c("local"))),as.numeric(as.data.frame(t(as.data.frame(cif.bar15)))$trans))
cif.bar.tt16 <- t.test(!is.na(transitivity(cif16, type=c("local"))),as.numeric(as.data.frame(t(as.data.frame(cif.bar16)))$trans))
cif.bar.tt17 <- t.test(!is.na(transitivity(cif17, type=c("local"))),as.numeric(as.data.frame(t(as.data.frame(cif.bar17)))$trans))
cif.bar.tt18 <- t.test(!is.na(transitivity(cif18, type=c("local"))),as.numeric(as.data.frame(t(as.data.frame(cif.bar18)))$trans))
cif.bar.tt19 <- t.test(!is.na(transitivity(cif19, type=c("local"))),as.numeric(as.data.frame(t(as.data.frame(cif.bar19)))$trans))
cif.bar.tt20 <- t.test(!is.na(transitivity(cif20, type=c("local"))),as.numeric(as.data.frame(t(as.data.frame(cif.bar20)))$trans))
cif.bar.tt21 <- t.test(!is.na(transitivity(cif21, type=c("local"))),as.numeric(as.data.frame(t(as.data.frame(cif.bar21)))$trans))
cif.bar.tt22 <- t.test(!is.na(transitivity(cif22, type=c("local"))),as.numeric(as.data.frame(t(as.data.frame(cif.bar22)))$trans))

### Erdos

cif.erdos.tt1 <- t.test(!is.na(transitivity(cif1, type=c("local"))),as.numeric(as.data.frame(t(as.data.frame(erdos.cif1)))$trans))
cif.erdos.tt2 <- t.test(!is.na(transitivity(cif2, type=c("local"))),as.numeric(as.data.frame(t(as.data.frame(erdos.cif2)))$trans))
cif.erdos.tt3 <- t.test(!is.na(transitivity(cif3, type=c("local"))),as.numeric(as.data.frame(t(as.data.frame(erdos.cif3)))$trans))
cif.erdos.tt4 <- t.test(!is.na(transitivity(cif4, type=c("local"))),as.numeric(as.data.frame(t(as.data.frame(erdos.cif4)))$trans))
cif.erdos.tt5 <- t.test(!is.na(transitivity(cif5, type=c("local"))),as.numeric(as.data.frame(t(as.data.frame(erdos.cif5)))$trans))
cif.erdos.tt6 <- t.test(!is.na(transitivity(cif6, type=c("local"))),as.numeric(as.data.frame(t(as.data.frame(erdos.cif6)))$trans))
cif.erdos.tt7 <- t.test(!is.na(transitivity(cif7, type=c("local"))),as.numeric(as.data.frame(t(as.data.frame(erdos.cif7)))$trans))
cif.erdos.tt8 <- t.test(!is.na(transitivity(cif8, type=c("local"))),as.numeric(as.data.frame(t(as.data.frame(erdos.cif8)))$trans))
cif.erdos.tt9 <- t.test(!is.na(transitivity(cif9, type=c("local"))),as.numeric(as.data.frame(t(as.data.frame(erdos.cif9)))$trans))
cif.erdos.tt10 <- t.test(!is.na(transitivity(cif10, type=c("local"))),as.numeric(as.data.frame(t(as.data.frame(erdos.cif10)))$trans))
cif.erdos.tt11 <- t.test(!is.na(transitivity(cif11, type=c("local"))),as.numeric(as.data.frame(t(as.data.frame(erdos.cif11)))$trans))
cif.erdos.tt12 <- t.test(!is.na(transitivity(cif12, type=c("local"))),as.numeric(as.data.frame(t(as.data.frame(erdos.cif12)))$trans))
cif.erdos.tt13 <- t.test(!is.na(transitivity(cif13, type=c("local"))),as.numeric(as.data.frame(t(as.data.frame(erdos.cif13)))$trans))
cif.erdos.tt14 <- t.test(!is.na(transitivity(cif14, type=c("local"))),as.numeric(as.data.frame(t(as.data.frame(erdos.cif14)))$trans))
cif.erdos.tt15 <- t.test(!is.na(transitivity(cif15, type=c("local"))),as.numeric(as.data.frame(t(as.data.frame(erdos.cif15)))$trans))
cif.erdos.tt16 <- t.test(!is.na(transitivity(cif16, type=c("local"))),as.numeric(as.data.frame(t(as.data.frame(erdos.cif16)))$trans))
cif.erdos.tt17 <- t.test(!is.na(transitivity(cif17, type=c("local"))),as.numeric(as.data.frame(t(as.data.frame(erdos.cif17)))$trans))
cif.erdos.tt18 <- t.test(!is.na(transitivity(cif18, type=c("local"))),as.numeric(as.data.frame(t(as.data.frame(erdos.cif18)))$trans))
cif.erdos.tt19 <- t.test(!is.na(transitivity(cif19, type=c("local"))),as.numeric(as.data.frame(t(as.data.frame(erdos.cif19)))$trans))
cif.erdos.tt20 <- t.test(!is.na(transitivity(cif20, type=c("local"))),as.numeric(as.data.frame(t(as.data.frame(erdos.cif20)))$trans))
cif.erdos.tt21 <- t.test(!is.na(transitivity(cif21, type=c("local"))),as.numeric(as.data.frame(t(as.data.frame(erdos.cif21)))$trans))
cif.erdos.tt22 <- t.test(!is.na(transitivity(cif22, type=c("local"))),as.numeric(as.data.frame(t(as.data.frame(erdos.cif22)))$trans))

### Watts

cif.watts.tt1 <- t.test(!is.na(transitivity(cif1, type=c("local"))),as.numeric(as.data.frame(t(as.data.frame(watts.cif1)))$trans))
cif.watts.tt2 <- t.test(!is.na(transitivity(cif2, type=c("local"))),as.numeric(as.data.frame(t(as.data.frame(watts.cif2)))$trans))
cif.watts.tt3 <- t.test(!is.na(transitivity(cif3, type=c("local"))),as.numeric(as.data.frame(t(as.data.frame(watts.cif3)))$trans))
cif.watts.tt4 <- t.test(!is.na(transitivity(cif4, type=c("local"))),as.numeric(as.data.frame(t(as.data.frame(watts.cif4)))$trans))
cif.watts.tt5 <- t.test(!is.na(transitivity(cif5, type=c("local"))),as.numeric(as.data.frame(t(as.data.frame(watts.cif5)))$trans))
cif.watts.tt6 <- t.test(!is.na(transitivity(cif6, type=c("local"))),as.numeric(as.data.frame(t(as.data.frame(watts.cif6)))$trans))
cif.watts.tt7 <- t.test(!is.na(transitivity(cif7, type=c("local"))),as.numeric(as.data.frame(t(as.data.frame(watts.cif7)))$trans))
cif.watts.tt8 <- t.test(!is.na(transitivity(cif8, type=c("local"))),as.numeric(as.data.frame(t(as.data.frame(watts.cif8)))$trans))
cif.watts.tt9 <- t.test(!is.na(transitivity(cif9, type=c("local"))),as.numeric(as.data.frame(t(as.data.frame(watts.cif9)))$trans))
cif.watts.tt10 <- t.test(!is.na(transitivity(cif10, type=c("local"))),as.numeric(as.data.frame(t(as.data.frame(watts.cif10)))$trans))
cif.watts.tt11 <- t.test(!is.na(transitivity(cif11, type=c("local"))),as.numeric(as.data.frame(t(as.data.frame(watts.cif11)))$trans))
cif.watts.tt12 <- t.test(!is.na(transitivity(cif12, type=c("local"))),as.numeric(as.data.frame(t(as.data.frame(watts.cif12)))$trans))
cif.watts.tt13 <- t.test(!is.na(transitivity(cif13, type=c("local"))),as.numeric(as.data.frame(t(as.data.frame(watts.cif13)))$trans))
cif.watts.tt14 <- t.test(!is.na(transitivity(cif14, type=c("local"))),as.numeric(as.data.frame(t(as.data.frame(watts.cif14)))$trans))
cif.watts.tt15 <- t.test(!is.na(transitivity(cif15, type=c("local"))),as.numeric(as.data.frame(t(as.data.frame(watts.cif15)))$trans))
cif.watts.tt16 <- t.test(!is.na(transitivity(cif16, type=c("local"))),as.numeric(as.data.frame(t(as.data.frame(watts.cif16)))$trans))
cif.watts.tt17 <- t.test(!is.na(transitivity(cif17, type=c("local"))),as.numeric(as.data.frame(t(as.data.frame(watts.cif17)))$trans))
cif.watts.tt18 <- t.test(!is.na(transitivity(cif18, type=c("local"))),as.numeric(as.data.frame(t(as.data.frame(watts.cif18)))$trans))
cif.watts.tt19 <- t.test(!is.na(transitivity(cif19, type=c("local"))),as.numeric(as.data.frame(t(as.data.frame(watts.cif19)))$trans))
cif.watts.tt20 <- t.test(!is.na(transitivity(cif20, type=c("local"))),as.numeric(as.data.frame(t(as.data.frame(watts.cif20)))$trans))
cif.watts.tt21 <- t.test(!is.na(transitivity(cif21, type=c("local"))),as.numeric(as.data.frame(t(as.data.frame(watts.cif21)))$trans))
cif.watts.tt22 <- t.test(!is.na(transitivity(cif22, type=c("local"))),as.numeric(as.data.frame(t(as.data.frame(watts.cif22)))$trans))

cif.test  <-  as.data.frame(c(cif.bar.ct1$p.value,cif.bar.ct2$p.value,cif.bar.ct3$p.value,cif.bar.ct4$p.value,cif.bar.ct5$p.value,cif.bar.ct6$p.value,cif.bar.ct7$p.value,cif.bar.ct8$p.value,cif.bar.ct9$p.value,cif.bar.ct10$p.value, cif.bar.ct11$p.value, cif.bar.ct12$p.value, cif.bar.ct13$p.value, cif.bar.ct14$p.value, cif.bar.ct15$p.value, cif.bar.ct16$p.value, cif.bar.ct17$p.value, cif.bar.ct18$p.value, cif.bar.ct19$p.value, cif.bar.ct20$p.value, cif.bar.ct21$p.value, cif.bar.ct22$p.value))
colnames(cif.test)[1] <- "constraint.bar"
cif.test$constraint.erdos <- (c(cif.erdos.ct1$p.value,cif.erdos.ct2$p.value,cif.erdos.ct3$p.value,cif.erdos.ct4$p.value,cif.erdos.ct5$p.value,cif.erdos.ct6$p.value,cif.erdos.ct7$p.value,cif.erdos.ct8$p.value,cif.erdos.ct9$p.value,cif.erdos.ct10$p.value, cif.erdos.ct11$p.value, cif.erdos.ct12$p.value, cif.erdos.ct13$p.value, cif.erdos.ct14$p.value, cif.erdos.ct15$p.value, cif.erdos.ct16$p.value, cif.erdos.ct17$p.value, cif.erdos.ct18$p.value, cif.erdos.ct19$p.value, cif.erdos.ct20$p.value, cif.erdos.ct21$p.value, cif.erdos.ct22$p.value))
cif.test$constraint.watts <- (c(cif.watts.ct1$p.value,cif.watts.ct2$p.value,cif.watts.ct3$p.value,cif.watts.ct4$p.value,cif.watts.ct5$p.value,cif.watts.ct6$p.value,cif.watts.ct7$p.value,cif.watts.ct8$p.value,cif.watts.ct9$p.value,cif.watts.ct10$p.value, cif.watts.ct11$p.value, cif.watts.ct12$p.value, cif.watts.ct13$p.value, cif.watts.ct14$p.value, cif.watts.ct15$p.value, cif.watts.ct16$p.value, cif.watts.ct17$p.value, cif.watts.ct18$p.value, cif.watts.ct19$p.value, cif.watts.ct20$p.value, cif.watts.ct21$p.value, cif.watts.ct22$p.value))
cif.test$trans.bar <- (c(cif.bar.tt1$p.value,cif.bar.tt2$p.value,cif.bar.tt3$p.value,cif.bar.tt4$p.value,cif.bar.tt5$p.value,cif.bar.tt6$p.value,cif.bar.tt7$p.value,cif.bar.tt8$p.value,cif.bar.tt9$p.value,cif.bar.tt10$p.value, cif.bar.tt11$p.value, cif.bar.tt12$p.value, cif.bar.tt13$p.value, cif.bar.tt14$p.value, cif.bar.tt15$p.value, cif.bar.tt16$p.value, cif.bar.tt17$p.value, cif.bar.tt18$p.value, cif.bar.tt19$p.value, cif.bar.tt20$p.value, cif.bar.tt21$p.value, cif.bar.tt22$p.value))
cif.test$trans.erdos <- (c(cif.erdos.tt1$p.value,cif.erdos.tt2$p.value,cif.erdos.tt3$p.value,cif.erdos.tt4$p.value,cif.erdos.tt5$p.value,cif.erdos.tt6$p.value,cif.erdos.tt7$p.value,cif.erdos.tt8$p.value,cif.erdos.tt9$p.value,cif.erdos.tt10$p.value, cif.erdos.tt11$p.value, cif.erdos.tt12$p.value, cif.erdos.tt13$p.value, cif.erdos.tt14$p.value, cif.erdos.tt15$p.value, cif.erdos.tt16$p.value, cif.erdos.tt17$p.value, cif.erdos.tt18$p.value, cif.erdos.tt19$p.value, cif.erdos.tt20$p.value, cif.erdos.tt21$p.value, cif.erdos.tt22$p.value))
cif.test$trans.watts <- (c(cif.watts.tt1$p.value,cif.watts.tt2$p.value,cif.watts.tt3$p.value,cif.watts.tt4$p.value,cif.watts.tt5$p.value,cif.watts.tt6$p.value,cif.watts.tt7$p.value,cif.watts.tt8$p.value,cif.watts.tt9$p.value,cif.watts.tt10$p.value, cif.watts.tt11$p.value, cif.watts.tt12$p.value, cif.watts.tt13$p.value, cif.watts.tt14$p.value, cif.watts.tt15$p.value, cif.watts.tt16$p.value, cif.watts.tt17$p.value, cif.watts.tt18$p.value, cif.watts.tt19$p.value, cif.watts.tt20$p.value, cif.watts.tt21$p.value, cif.watts.tt22$p.value))

View(cif.test)

